### ISSUE TITLE
Can't execute http request

### ISSUE THREAD

**Issue by Odonno** [deltakosh/JsBridge#13]
I tried to make an HTTP call using XmlHttpRequest object but I receive an error each time I try to send the request. Here is the error : 

![capture](https://cloud.githubusercontent.com/assets/6053067/14588402/269ed08c-04c9-11e6-9014-c04df69cc788.PNG)

**Comment by deltakosh** [comment]
Hello, looks like your responseText is null

**Comment by gleborgne** [comment]
by looking at your code in the capture, your error is likely to be in your javascript. xhr.send is asynchronous, though you had better check the state of your call before trying to read content

**Comment by Odonno** [comment]
@gleborgne Indeed, it is because the call is async. I made a callback function and it works now. Sorry for my mistake.

Thank you very much @deltakosh and @gleborgne
